"""Wave-4 crypto byte-parity tests.

Vectors were generated by running the real ``better-auth@1.6.23`` (XChaCha20-Poly1305
``symmetricEncrypt``, ``@better-auth/utils`` ``createOTP``) and are hardcoded here so the
suite never depends on a Node runtime. A passing suite proves the Python port is
byte-for-byte cross-runtime compatible: a token encrypted / an OTP generated by a
TypeScript better-auth app is accepted by this port and vice-versa.
"""

import base64
import hashlib
import hmac
import json
import math
import re

import pytest
from nacl.exceptions import CryptoError

from better_auth.crypto import (
    decode_jwk_private_key,
    encode_jwk_private_key,
    generate_ed25519_jwk_pair,
    generate_hotp,
    generate_totp,
    is_likely_encrypted,
    otpauth_url,
    sign_hmac_b64url,
    symmetric_decrypt,
    symmetric_encrypt,
    verify_totp,
)

# --- ground-truth vectors (real better-auth@1.6.23) ------------------------------------

SYM_SECRET = "better-auth-secret-123"
SYM_PLAINTEXT = "hello cross-runtime parity"
SYM_HEX = (
    "9537756d85bb58ebf1d21f10cc5c067c426a3a2cbaaf10b1b1cbebd47aa6c7de"
    "261e69a231da101f07996df452dcba53a3362badbd7a1173d30c3b37055d6bbf0022"
)
# key rotation envelope: "$ba$<version>$<hex>"; version 2 key == SYM_SECRET
ENVELOPE_KEYS = {1: "old-secret", 2: "better-auth-secret-123"}
ENVELOPE_VALUE = (
    "$ba$2$d7a716603d6cd7bceb6080f3f5cba34b3f5978b03da2dccd9a2535fd1c6c3cfd"
    "934919c5aaebc82cba717b2fa0c29386e4864266d7c8abfaf2994a952a28a2367889"
)

HOTP_SECRET = "test-totp-secret-key"
HOTP_VECTORS = [
    (0, 6, "507628"),
    (1, 6, "607121"),
    (42, 6, "728398"),
    (59, 6, "039261"),
    (1111111111, 6, "026207"),
    (0, 8, "32507628"),
    (1, 8, "56607121"),
    (42, 8, "29728398"),
    (59, 8, "84039261"),
    (1111111111, 8, "01026207"),
]

OTPAUTH_URL = (
    "otpauth://totp/MyIssuer:user%40example.com"
    "?secret=ORSXG5BNORXXI4BNONSWG4TFOQWWWZLZ&issuer=MyIssuer&digits=6&period=30"
)

HMAC_KEY = "better-auth-secret-123"
HMAC_DATA = "hello cross-runtime parity"
HMAC_SHA256_HEX = "9c2fb7532f09afa03269aa536a29b64120a142c94f405f89893933c3971e74cc"
HMAC_SHA256_B64URLNOPAD = "nC-3Uy8Jr6AyaapTaim2QSChQslPQF-JiTkzw5cedMw"


# --- symmetric_encrypt / symmetric_decrypt ---------------------------------------------


def test_symmetric_decrypt_ts_vector():
    # decrypts a ciphertext produced by the real TS better-auth XChaCha20-Poly1305
    assert symmetric_decrypt(SYM_SECRET, SYM_HEX) == SYM_PLAINTEXT


def test_symmetric_envelope_decrypt_with_keys():
    assert symmetric_decrypt(SYM_SECRET, ENVELOPE_VALUE, keys=ENVELOPE_KEYS) == SYM_PLAINTEXT


def test_symmetric_envelope_unknown_version_raises():
    with pytest.raises(ValueError, match="version"):
        symmetric_decrypt(SYM_SECRET, ENVELOPE_VALUE, keys={1: "old-secret"})


def test_symmetric_envelope_without_keys_raises():
    with pytest.raises(ValueError, match="version"):
        symmetric_decrypt(SYM_SECRET, ENVELOPE_VALUE)


def test_symmetric_round_trip():
    ct = symmetric_encrypt(SYM_SECRET, SYM_PLAINTEXT)
    assert re.fullmatch(r"[0-9a-f]+", ct)  # bare lowercase hex, no envelope prefix
    assert len(ct) >= 132  # 24-byte nonce + ct + 16-byte tag, hex-encoded
    assert symmetric_decrypt(SYM_SECRET, ct) == SYM_PLAINTEXT


def test_symmetric_random_nonce():
    # managedNonce prepends a fresh random nonce each call -> different ciphertext
    assert symmetric_encrypt(SYM_SECRET, SYM_PLAINTEXT) != symmetric_encrypt(
        SYM_SECRET, SYM_PLAINTEXT
    )


def test_symmetric_tamper_raises():
    ct = symmetric_encrypt(SYM_SECRET, SYM_PLAINTEXT)
    i = 60  # a nibble inside the ciphertext body
    flipped = ct[:i] + ("1" if ct[i] == "0" else "0") + ct[i + 1 :]
    with pytest.raises(CryptoError):
        symmetric_decrypt(SYM_SECRET, flipped)


def test_symmetric_wrong_secret_raises():
    ct = symmetric_encrypt(SYM_SECRET, SYM_PLAINTEXT)
    with pytest.raises(CryptoError):
        symmetric_decrypt("some-other-secret", ct)


def test_is_likely_encrypted():
    assert is_likely_encrypted(symmetric_encrypt(SYM_SECRET, SYM_PLAINTEXT))
    assert is_likely_encrypted(ENVELOPE_VALUE)
    assert not is_likely_encrypted("ya29.a0AfB_plain_oauth_access_token")
    assert not is_likely_encrypted("deadbeef")  # too short to be a ciphertext


# --- HOTP / TOTP -----------------------------------------------------------------------


@pytest.mark.parametrize(("counter", "digits", "expected"), HOTP_VECTORS)
def test_generate_hotp_vectors(counter, digits, expected):
    assert generate_hotp(HOTP_SECRET, counter, digits=digits) == expected


def test_totp_equals_hotp_at_floor_counter():
    now = 1_700_000_000  # seconds
    assert generate_totp(HOTP_SECRET, now=now) == generate_hotp(HOTP_SECRET, now // 30)
    assert generate_totp(HOTP_SECRET, now=now, period=60) == generate_hotp(
        HOTP_SECRET, now // 60
    )


def test_totp_default_now_uses_wall_clock():
    # smoke: no injected now -> uses time.time(); 6 digits
    assert re.fullmatch(r"\d{6}", generate_totp(HOTP_SECRET))


def test_verify_totp_window():
    now = 1000  # counter = floor(1000/30) = 33
    otp = generate_hotp(HOTP_SECRET, now // 30)
    assert verify_totp(otp, secret=HOTP_SECRET, now=now)  # i = 0
    assert verify_totp(otp, secret=HOTP_SECRET, now=now + 30)  # counter 34, window covers 33
    assert verify_totp(otp, secret=HOTP_SECRET, now=now - 30)  # counter 32, window covers 33
    assert not verify_totp(otp, secret=HOTP_SECRET, now=now + 60)  # counter 35, out of window 1
    assert not verify_totp(otp, secret=HOTP_SECRET, now=now + 30, window=0)  # only counter 34
    assert not verify_totp("000000", secret=HOTP_SECRET, now=now)  # wrong code


def test_verify_totp_wider_window():
    now = 1000
    otp = generate_hotp(HOTP_SECRET, now // 30)
    assert verify_totp(otp, secret=HOTP_SECRET, now=now + 60, window=2)  # now in +/-2


@pytest.mark.parametrize("digits", [0, 9, -1, 100])
def test_generate_hotp_digit_bounds_raise(digits):
    with pytest.raises(ValueError, match="between 1 and 8"):
        generate_hotp(HOTP_SECRET, 0, digits=digits)


def test_otpauth_url_vector():
    assert (
        otpauth_url("test-totp-secret-key", "MyIssuer", "user@example.com") == OTPAUTH_URL
    )


# --- HMAC (cookie-signature cross-compat) ----------------------------------------------


def test_hmac_sha256_hex_vector():
    got = hmac.new(HMAC_KEY.encode(), HMAC_DATA.encode(), hashlib.sha256).hexdigest()
    assert got == HMAC_SHA256_HEX


def test_hmac_sha256_b64urlnopad_vector():
    assert sign_hmac_b64url(HMAC_KEY, HMAC_DATA) == HMAC_SHA256_B64URLNOPAD


# --- Ed25519 / JWKS key material -------------------------------------------------------


def test_generate_ed25519_jwk_pair_shape():
    public_jwk, private_jwk = generate_ed25519_jwk_pair()
    # jose exportJWK(Ed25519) field set: OKP public {kty,crv,x}; private adds d
    assert public_jwk == {"kty": "OKP", "crv": "Ed25519", "x": public_jwk["x"]}
    assert set(private_jwk) == {"kty", "crv", "x", "d"}
    assert private_jwk["kty"] == "OKP"
    assert private_jwk["crv"] == "Ed25519"
    assert private_jwk["x"] == public_jwk["x"]  # public component matches
    # x and d are base64url-nopad of 32-byte Ed25519 values (43 chars, no '=' padding)
    for field in ("x", "d"):
        val = private_jwk[field]
        assert "=" not in val and len(val) == 43
        assert len(base64.urlsafe_b64decode(val + "==")) == 32


def test_jwk_private_key_storage_round_trip():
    _public_jwk, private_jwk = generate_ed25519_jwk_pair()
    stored = encode_jwk_private_key(SYM_SECRET, private_jwk)
    # TS format (jwt/utils.ts:74-81): JSON.stringify(symmetricEncrypt(JSON.stringify(jwk)))
    # -> a JSON-quoted string wrapping the bare-hex ciphertext.
    ciphertext = json.loads(stored)
    assert isinstance(ciphertext, str)
    assert re.fullmatch(r"[0-9a-f]+", ciphertext)
    assert decode_jwk_private_key(SYM_SECRET, stored) == private_jwk


def test_jwk_private_key_decode_ts_layout():
    # a value written by TS (plain-string secret path) is read back to the JWK
    jwk = {"kty": "OKP", "crv": "Ed25519", "x": "abc", "d": "def"}
    stored = json.dumps(symmetric_encrypt(SYM_SECRET, json.dumps(jwk)))
    assert decode_jwk_private_key(SYM_SECRET, stored) == jwk


assert math.floor(1000 / 30) == 33  # sanity: window-test counter math
