"""device-authorization plugin — OAuth 2.0 Device Authorization Grant (RFC 8628).

TV/CLI login: a device mints a `device_code`/`user_code` pair, shows the user_code to
the user, and polls `/device/token` while the user visits `/device` on a second screen
(phone/laptop) to approve or deny it.

Verified against TS ``packages/better-auth/src/plugins/device-authorization/``
(``index.ts``, ``routes.ts``, ``schema.ts``, ``error-codes.ts``) at v1.7.6. Every error
in this plugin is OAuth-shaped on the wire (``{"error": ..., "error_description": ...}``,
RFC 6749 style) rather than this port's generic ``{"code", "message"}`` APIError body, so
errors travel as :class:`DeviceAuthorizationError` and render through ``to_response``.

A :class:`DeviceAuthorizationGrant` (TS ``DeviceAuthorizationGrant``) lets a token issuer
such as the OAuth provider own some codes: it authorizes the request, adds its own
``deviceCode`` columns, keeps its codes out of ``/device/token`` and adds owner-only context
to ``GET /device``. :func:`redeem_device_code` is the polling and one-time claim state machine
every issuer shares.

Redemption of an approved code is atomic (``adapter.consume_one`` — delete-and-return, TS
``consumeOne``): concurrent pollers race on the same delete, exactly one wins the row, every
other caller gets ``None`` back and is rejected. The `/device` claim of a pending, unbound
code and the `/device/token` polling-interval bump both use ``adapter.increment_one``
(guarded compare-and-swap, TS ``incrementOne``) so a stale read can never clobber a write
that landed first. This closes the same race TS's own GHSA-cq3f-vc6p-68fh fix targets, and
hardens the (TS-unguarded) `lastPolledAt` bump the same way.
"""

from __future__ import annotations

import inspect
import re
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from datetime import timedelta
from typing import Any, ClassVar
from urllib.parse import parse_qsl, urlencode, urljoin, urlsplit, urlunsplit

from ..adapters.base import Where
from ..crypto import generate_random_string
from ..plugins import Plugin, RateLimitRule, Route
from ..schema import Field, Schema
from ..session import utcnow
from ..types import APIError, AuthResponse, Ctx

#: TS ``DEVICE_AUTHORIZATION_ERROR_CODES`` (error-codes.ts) — exact strings, surfaced on
#: ``auth.error_codes``. These are the internal error *messages*; the wire-visible OAuth
#: error *codes* (``slow_down``, ``invalid_grant``, ...) are the literals used below.
ERROR_CODES: dict[str, str] = {
    "INVALID_DEVICE_CODE": "Invalid device code",
    "EXPIRED_DEVICE_CODE": "Device code has expired",
    "EXPIRED_USER_CODE": "User code has expired",
    "AUTHORIZATION_PENDING": "Authorization pending",
    "ACCESS_DENIED": "Access denied",
    "INVALID_USER_CODE": "Invalid user code",
    "DEVICE_CODE_ALREADY_PROCESSED": "Device code already processed",
    "DEVICE_CODE_NOT_CLAIMED": (
        "Device code has not been claimed by a verifying session; call `GET /device` "
        "with the `user_code` while signed in before approving or denying"
    ),
    "POLLING_TOO_FREQUENTLY": "Polling too frequently",
    "USER_NOT_FOUND": "User not found",
    "FAILED_TO_CREATE_SESSION": "Failed to create session",
    "INVALID_DEVICE_CODE_STATUS": "Invalid device code status",
    "AUTHENTICATION_REQUIRED": "Authentication required",
}

#: Longest generated code the indexed columns accept (TS schema.ts:4, 49b5cf650).
DEVICE_AUTHORIZATION_CODE_MAX_LENGTH = 191

#: TS ``schema.ts``: no ``id``/``createdAt``/``updatedAt`` declared, matching TS exactly
#: (``id`` is auto-generated by the adapter). ``deviceCode`` and ``userCode`` carry TS's
#: unique lookup indexes (``deviceCode_deviceCode_uidx``, ``deviceCode_userCode_uidx``).
DEVICE_AUTHORIZATION_SCHEMA: Schema = {
    "deviceCode": {
        "deviceCode": Field("string", required=True, unique=True),
        "userCode": Field("string", required=True, unique=True),
        "userId": Field("string", required=False),
        "expiresAt": Field("datetime", required=True),
        "status": Field("string", required=True),
        "lastPolledAt": Field("datetime", required=False),
        "pollingInterval": Field("number", required=False),
        "clientId": Field("string", required=False),
        "scope": Field("string", required=False),
    },
}

_GRANT_TYPE = "urn:ietf:params:oauth:grant-type:device_code"
#: TS ``generateRandomString(length, "a-z", "A-Z", "0-9")`` (routes.ts defaultGenerateDeviceCode).
_DEVICE_CODE_ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
#: TS ``defaultCharset`` (routes.ts) — Crockford-ish, no ambiguous I/O/0/1.
_USER_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
_DEFAULT_USER_CODE = re.compile(f"^[{_USER_CODE_ALPHABET}]+$", re.IGNORECASE)
_MAX_GENERATION_ATTEMPTS = 3
#: TS ``isUniqueConstraintError`` message test (routes.ts:34).
_UNIQUE_VIOLATION = re.compile(
    r"unique(?: key)? constraint|duplicate (?:entry|key)|e11000", re.IGNORECASE
)
_BASE_REQUEST_FIELDS = ("client_id", "user_id", "scope")
_NO_STORE = [("Cache-Control", "no-store"), ("Pragma", "no-cache")]

# --- time-string parsing (TS utils/time.ts `ms()`, positive-duration subset) -----------
#
# ponytail: expiresIn/interval are always positive durations for this plugin, so the sign
# prefix ("+"/"-") and "ago"/"from now" suffix TS's `ms()` also accepts are skipped here —
# add if a config value ever needs relative/negative time semantics (it doesn't today).

_SEC = 1000
_MIN = _SEC * 60
_HOUR = _MIN * 60
_DAY = _HOUR * 24
_WEEK = _DAY * 7
_MONTH = _DAY * 30
_YEAR = _DAY * 365.25

_UNIT_MS: dict[str, float] = {
    "s": _SEC, "sec": _SEC, "secs": _SEC, "second": _SEC, "seconds": _SEC,
    "m": _MIN, "min": _MIN, "mins": _MIN, "minute": _MIN, "minutes": _MIN,
    "h": _HOUR, "hr": _HOUR, "hrs": _HOUR, "hour": _HOUR, "hours": _HOUR,
    "d": _DAY, "day": _DAY, "days": _DAY,
    "w": _WEEK, "week": _WEEK, "weeks": _WEEK,
    "mo": _MONTH, "month": _MONTH, "months": _MONTH,
    "y": _YEAR, "yr": _YEAR, "yrs": _YEAR, "year": _YEAR, "years": _YEAR,
}  # fmt: skip

_TIME_RE = re.compile(
    r"^(\d+|\d+\.\d+) ?"
    r"(seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|w|months?|mo|years?|yrs?|y)$",
    re.IGNORECASE,
)


def _parse_time_ms(value: str) -> int:
    """``"30m"``/``"5s"``/``"1h"`` -> milliseconds (TS ``ms()``, utils/time.ts). Raises
    ``ValueError`` on an unparseable string — the eager-validation equivalent of zod's
    ``deviceAuthorizationOptionsSchema.parse()`` throwing at plugin construction."""
    if not isinstance(value, str):
        raise ValueError(f"Invalid time string format: {value!r}")
    match = _TIME_RE.match(value.strip())
    if not match:
        raise ValueError(
            f'Invalid time string format: "{value}". Use formats like "30m", "5s", "1h", etc.'
        )
    amount = float(match.group(1))
    unit = match.group(2).lower()
    return round(amount * _UNIT_MS[unit])


async def _maybe_await(value: Any) -> Any:
    return await value if inspect.isawaitable(value) else value


class DeviceAuthorizationError(Exception):
    """An RFC 6749 shaped error (``{error, error_description}``). The core dispatcher renders
    ``APIError`` as ``{code, message}``, so routes turn this into a response themselves."""

    def __init__(
        self,
        status: int,
        error: str,
        description: str,
        headers: list[tuple[str, str]] | None = None,
    ) -> None:
        super().__init__(description)
        self.status = status
        self.error = error
        self.description = description
        self.headers = headers

    def to_response(self) -> AuthResponse:
        return AuthResponse(
            status=self.status,
            body={"error": self.error, "error_description": self.description},
            headers=list(self.headers or []),
        )


def _fail(status: int, error: str, description: str) -> DeviceAuthorizationError:
    return DeviceAuthorizationError(status, error, description)


@dataclass
class DeviceAuthorizationGrant:
    """A token grant that owns some device codes (TS ``DeviceAuthorizationGrant``,
    index.ts:156). Hooks take ``(ctx, ...)`` and may be sync or async. A plugin subclass
    declares the grant's extra ``deviceCode`` columns on its ``schema`` (index.ts:252)."""

    #: extra ``/device/code`` body fields accepted only with this grant
    request_fields: tuple[str, ...]
    #: ``(ctx, request) -> {"clientId", "deviceCodeFields"} | None``
    authorize_request: Callable[[Ctx, dict[str, Any]], Awaitable[dict[str, Any] | None]]
    #: ``(ctx, record) -> None``; raises to keep a grant code out of ``/device/token``
    assert_session_redemption: Callable[[Ctx, dict[str, Any]], None]
    #: ``(record) -> dict | None``: owner-only additions to ``GET /device``
    get_verification_context: Callable[[dict[str, Any]], dict[str, Any] | None]


def _request_body(ctx: Ctx) -> tuple[dict[str, Any], list[tuple[str, str]] | None]:
    """The JSON or form-encoded body (TS ``allowedMediaTypes``), plus the raw form pairs."""
    ctype = (ctx.request.headers.get("content-type") or "").lower()
    if "application/x-www-form-urlencoded" in ctype:
        pairs = parse_qsl(ctx.request.body.decode("utf-8", "replace"), keep_blank_values=True)
        return dict(pairs), pairs
    return dict(ctx.body()), None


def _normalize_base_request(body: dict[str, Any], pairs: list[tuple[str, str]] | None) -> None:
    """TS ``normalizeDeviceAuthorizationBaseRequestParameters`` (routes.ts:140): empty base
    fields are omitted, and a repeated non-empty form field is ``invalid_request``."""
    for name in _BASE_REQUEST_FIELDS:
        if body.get(name) == "":
            body[name] = None
    if pairs is None:
        return
    for name in _BASE_REQUEST_FIELDS:
        values = [v for k, v in pairs if k == name and v]
        if len(values) > 1:
            raise _fail(400, "invalid_request", f"{name} must not be repeated")
        body[name] = values[0] if values else None


def _is_unique_violation(error: Exception) -> bool:
    identifiers = {
        str(getattr(error, attr, "")) for attr in ("code", "errcode", "errno", "number", "pgcode")
    }
    known = {"11000", "1062", "2067", "23505", "2601", "2627", "ER_DUP_ENTRY", "P2002"}
    return bool(identifiers & (known | {"SQLITE_CONSTRAINT_UNIQUE"})) or bool(
        _UNIQUE_VIOLATION.search(str(error))
    )


def _validate_generated_code(code: Any, label: str) -> str:
    """TS ``validateGeneratedCode`` (routes.ts:56): a string of at most 191 code points."""
    if not isinstance(code, str):
        raise _fail(400, "invalid_request", f"Generated {label} code must be a string")
    if len(code) > DEVICE_AUTHORIZATION_CODE_MAX_LENGTH:
        raise _fail(
            400,
            "invalid_request",
            f"Generated {label} code must be at most "
            f"{DEVICE_AUTHORIZATION_CODE_MAX_LENGTH} characters",
        )
    return code


async def find_device_code_by_user_code(ctx: Ctx, user_code: str) -> dict[str, Any] | None:
    """TS ``findDeviceCodeByUserCode`` (routes.ts:78): exact match first; a default-alphabet
    code also matches with punctuation removed and letters upper-cased."""

    async def find(value: str) -> dict[str, Any] | None:
        record = await ctx.adapter.find_one("deviceCode", [Where("userCode", value)])
        return record if record and record.get("userCode") == value else None

    exact = await find(user_code)
    if exact:
        return exact
    normalized = re.sub(r"[^a-zA-Z0-9]", "", user_code).upper()
    if normalized == user_code or not _DEFAULT_USER_CODE.match(normalized):
        return None
    return await find(normalized)


async def redeem_device_code(
    ctx: Ctx,
    device_code: str,
    authorize_redemption: Callable[[dict[str, Any]], Awaitable[tuple[Where, Any]]],
    prepare_redemption: Callable[[dict[str, Any], Any], Awaitable[Any]],
) -> dict[str, Any]:
    """The RFC 8628 polling and one-time claim state machine shared by every token issuer,
    TS ``redeemDeviceCode`` (routes.ts:522). ``authorize_redemption(record)`` returns the
    ownership ``Where`` for the atomic claim and an issuer context. Returns ``{claimed,
    context, redemption, user}``; raises :class:`DeviceAuthorizationError`."""
    record = await ctx.adapter.find_one("deviceCode", [Where("deviceCode", device_code)])
    if record is None:
        raise _fail(400, "invalid_grant", ERROR_CODES["INVALID_DEVICE_CODE"])

    ownership, context = await authorize_redemption(record)
    now = utcnow()
    if record.get("lastPolledAt") and record.get("pollingInterval"):
        elapsed_ms = (now - record["lastPolledAt"]).total_seconds() * 1000
        if elapsed_ms < record["pollingInterval"]:
            raise _fail(400, "slow_down", ERROR_CODES["POLLING_TOO_FREQUENTLY"])

    # Guarded bump (CAS on the previously-read lastPolledAt): a poll that raced us between
    # the read above and this write loses the guard and is treated as slow_down too.
    polled = await ctx.adapter.increment_one(
        "deviceCode",
        [Where("id", record["id"]), Where("lastPolledAt", record.get("lastPolledAt"), "eq")],
        set={"lastPolledAt": now},
    )
    if polled is None:
        raise _fail(400, "slow_down", ERROR_CODES["POLLING_TOO_FREQUENTLY"])

    if record["expiresAt"] < now:
        await ctx.adapter.delete("deviceCode", [Where("id", record["id"])])
        raise _fail(400, "expired_token", ERROR_CODES["EXPIRED_DEVICE_CODE"])
    if record["status"] == "pending":
        raise _fail(400, "authorization_pending", ERROR_CODES["AUTHORIZATION_PENDING"])
    if record["status"] == "denied":
        await ctx.adapter.delete("deviceCode", [Where("id", record["id"])])
        raise _fail(400, "access_denied", ERROR_CODES["ACCESS_DENIED"])
    if record["status"] != "approved" or not record.get("userId"):
        raise _fail(500, "server_error", ERROR_CODES["INVALID_DEVICE_CODE_STATUS"])

    redemption = await prepare_redemption(record, context)
    user = await ctx.adapter.find_one("user", [Where("id", record["userId"])])
    if user is None:
        raise _fail(500, "server_error", ERROR_CODES["USER_NOT_FOUND"])
    # Every fallible check runs before this destructive claim; concurrent polls cannot both
    # issue from the same code.
    claimed = await ctx.adapter.consume_one(
        "deviceCode", [Where("id", record["id"]), ownership, Where("status", "approved")]
    )
    if not claimed or not claimed.get("userId"):
        raise _fail(400, "invalid_grant", ERROR_CODES["INVALID_DEVICE_CODE"])
    return {"claimed": claimed, "context": context, "redemption": redemption, "user": user}


def _build_verification_uris(
    verification_uri: str | None, base_url: str, user_code: str
) -> tuple[str, str]:
    """Resolve ``verification_uri`` (default ``/device``) against ``base_url`` (TS ``new
    URL(uri) | new URL(uri, baseURL)``) and derive the ``...?user_code=`` variant,
    preserving any query params the configured URI already carries."""
    resolved = urljoin(base_url, verification_uri or "/device")
    parts = urlsplit(resolved)
    params = [(k, v) for k, v in parse_qsl(parts.query, keep_blank_values=True) if k != "user_code"]
    params.append(("user_code", user_code))
    complete = urlunsplit(
        (parts.scheme, parts.netloc, parts.path, urlencode(params), parts.fragment)
    )
    return resolved, complete


def _handles_errors(handler: Callable[..., Awaitable[AuthResponse]], no_store: bool = False) -> Any:
    async def wrapped(ctx: Ctx) -> AuthResponse:
        try:
            return await handler(ctx)
        except DeviceAuthorizationError as error:
            response = error.to_response()
            if no_store:  # TS metadata.noStore covers handler errors (2196ea65e)
                present = {name.lower() for name, _ in response.headers}
                response.headers += [(k, v) for k, v in _NO_STORE if k.lower() not in present]
            return response
        except APIError as error:
            # TS core api/index.ts:101-118: a noStore handler's APIError carries them too.
            if no_store:
                headers = error.headers or []
                present = {name.lower() for name, _ in headers}
                error.headers = headers + [(k, v) for k, v in _NO_STORE if k.lower() not in present]
            raise

    return wrapped


class DeviceAuthorizationPlugin(Plugin):
    """TS ``deviceAuthorization()`` — see module docstring for the source files."""

    id = "device-authorization"
    schema: ClassVar[Schema] = DEVICE_AUTHORIZATION_SCHEMA
    error_codes: ClassVar[dict[str, str]] = ERROR_CODES

    def __init__(
        self,
        *,
        expires_in: str = "30m",
        interval: str = "5s",
        device_code_length: int = 40,
        user_code_length: int = 8,
        generate_device_code: Any = None,
        generate_user_code: Any = None,
        validate_client: Any = None,
        on_device_auth_request: Any = None,
        verification_uri: str | None = None,
        grant: DeviceAuthorizationGrant | None = None,
    ) -> None:
        _parse_time_ms(expires_in)
        _parse_time_ms(interval)
        for name, length in (
            ("device_code_length", device_code_length),
            ("user_code_length", user_code_length),
        ):
            if not isinstance(length, int) or length <= 0:
                raise ValueError(f"{name} must be a positive integer")
            if length > DEVICE_AUTHORIZATION_CODE_MAX_LENGTH:
                raise ValueError(
                    f"{name} must be at most {DEVICE_AUTHORIZATION_CODE_MAX_LENGTH} characters"
                )
        if verification_uri is not None and not isinstance(verification_uri, str):
            raise ValueError("verification_uri must be a string")
        self.expires_in = expires_in
        self.interval = interval
        self.device_code_length = device_code_length
        self.user_code_length = user_code_length
        self.generate_device_code = generate_device_code
        self.generate_user_code = generate_user_code
        self.validate_client = validate_client
        self.on_device_auth_request = on_device_auth_request
        self.verification_uri = verification_uri
        self.grant = grant

    def routes(self) -> list[Route]:
        return [
            ("POST", "/device/code", _handles_errors(self._device_code, no_store=True)),
            ("POST", "/device/token", _handles_errors(self._device_token, no_store=True)),
            ("GET", "/device", _handles_errors(self._device_verify)),
            ("POST", "/device/approve", _handles_errors(self._device_approve)),
            ("POST", "/device/deny", _handles_errors(self._device_deny)),
        ]

    def rate_limit(self) -> list[RateLimitRule]:
        # RFC 8628 §5.1 user-code guessing: five verifications per code lifetime (index.ts:264).
        window = _parse_time_ms(self.expires_in) // 1000
        return [RateLimitRule(window, 5, lambda path: path == "/device")]

    # --- code generation ----------------------------------------------------------------

    async def _generate_device_code(self) -> str:
        if self.generate_device_code is not None:
            code = await _maybe_await(self.generate_device_code())
        else:
            code = generate_random_string(self.device_code_length, alphabet=_DEVICE_CODE_ALPHABET)
        return _validate_generated_code(code, "device")

    async def _generate_user_code(self) -> str:
        if self.generate_user_code is not None:
            code = await _maybe_await(self.generate_user_code())
        else:
            code = generate_random_string(self.user_code_length, alphabet=_USER_CODE_ALPHABET)
        return _validate_generated_code(code, "user")

    # --- endpoints ------------------------------------------------------------------------

    async def _device_code(self, ctx: Ctx) -> AuthResponse:
        """POST /device/code, TS ``deviceCode`` (routes.ts:228)."""
        body, pairs = _request_body(ctx)
        allowed = (*_BASE_REQUEST_FIELDS, *(self.grant.request_fields if self.grant else ()))
        request = {k: v for k, v in body.items() if k in allowed}
        if self.grant is None and not isinstance(request.get("client_id"), str):
            raise _fail(400, "invalid_request", "'client_id' is required")
        _normalize_base_request(request, pairs)

        authorization = (
            await self.grant.authorize_request(ctx, request) if self.grant is not None else None
        )
        client_id = authorization["clientId"] if authorization else request.get("client_id")
        if authorization is None:
            if not request.get("client_id"):
                raise _fail(400, "invalid_request", "client_id is required")
            if self.validate_client is None:
                if self.grant is not None:
                    raise _fail(400, "invalid_client", "Invalid client ID")
            elif not await _maybe_await(self.validate_client(request["client_id"])):
                raise _fail(400, "invalid_client", "Invalid client ID")
        if not client_id:
            raise _fail(400, "invalid_request", "client_id is required")

        if self.on_device_auth_request is not None:
            await _maybe_await(self.on_device_auth_request(client_id, request.get("scope")))

        expires_in_ms = _parse_time_ms(self.expires_in)
        polling_interval_ms = _parse_time_ms(self.interval)
        expires_at = utcnow() + timedelta(milliseconds=expires_in_ms)
        for _ in range(_MAX_GENERATION_ATTEMPTS):
            device_code_value = await self._generate_device_code()
            user_code_value = await self._generate_user_code()
            try:
                await ctx.adapter.create(
                    "deviceCode",
                    {
                        **(authorization["deviceCodeFields"] if authorization else {}),
                        "deviceCode": device_code_value,
                        "userCode": user_code_value,
                        # an empty user_id is treated as omitted, per RFC 8628 section 3.1
                        "userId": request.get("user_id") or None,
                        "expiresAt": expires_at,
                        "status": "pending",
                        "pollingInterval": polling_interval_ms,
                        "clientId": client_id,
                        "scope": request.get("scope"),
                    },
                )
            except Exception as error:
                if not _is_unique_violation(error):
                    raise
                continue

            base_url = f"{ctx.auth.base_url}{ctx.auth.base_path}"
            verification_uri, verification_uri_complete = _build_verification_uris(
                self.verification_uri, base_url, user_code_value
            )
            return AuthResponse(
                body={
                    "device_code": device_code_value,
                    "user_code": user_code_value,
                    "verification_uri": verification_uri,
                    "verification_uri_complete": verification_uri_complete,
                    "expires_in": expires_in_ms // 1000,
                    "interval": polling_interval_ms // 1000,
                },
                headers=list(_NO_STORE),
            )
        raise _fail(500, "server_error", "Failed to generate a unique device code")

    async def _device_token(self, ctx: Ctx) -> AuthResponse:
        """POST /device/token: a first-party session token, TS ``deviceToken`` (routes.ts:680)."""
        body, _ = _request_body(ctx)
        grant_type = body.get("grant_type")
        device_code = body.get("device_code")
        client_id = body.get("client_id")
        if (
            grant_type != _GRANT_TYPE
            or not isinstance(device_code, str)
            or not isinstance(client_id, str)
        ):
            raise _fail(400, "invalid_request", "Invalid device token request")

        if self.validate_client is not None and not await _maybe_await(
            self.validate_client(client_id)
        ):
            raise _fail(400, "invalid_grant", "Invalid client ID")

        async def authorize(record: dict[str, Any]) -> tuple[Where, Any]:
            if record.get("clientId") and record["clientId"] != client_id:
                raise _fail(400, "invalid_grant", "Client ID mismatch")
            if self.grant is not None:
                await _maybe_await(self.grant.assert_session_redemption(ctx, record))
            return Where("clientId", client_id), None

        async def prepare(_record: dict[str, Any], _context: Any) -> None:
            return None

        result = await redeem_device_code(ctx, device_code, authorize, prepare)
        user = result["user"]
        session = await ctx.internal.create_session(user["id"])
        if session is None:
            raise _fail(500, "server_error", ERROR_CODES["FAILED_TO_CREATE_SESSION"])
        ctx.new_session = {"session": session, "user": user}
        expires_in = int((session["expiresAt"] - utcnow()).total_seconds())
        return AuthResponse(
            body={
                "access_token": session["token"],
                "token_type": "Bearer",
                "expires_in": expires_in,
                "scope": result["claimed"].get("scope") or "",
            },
            headers=list(_NO_STORE),
        )

    async def _device_verify(self, ctx: Ctx) -> AuthResponse:
        """GET /device, TS ``deviceVerify`` (routes.ts:810): the requesting client and scope
        are shown only to the signed-in user who owns the code."""
        user_code = ctx.request.query.get("user_code")
        if not user_code:
            raise _fail(400, "invalid_request", "'user_code' is required")
        record = await find_device_code_by_user_code(ctx, user_code)
        if record is None:
            raise _fail(400, "invalid_request", ERROR_CODES["INVALID_USER_CODE"])
        if record["expiresAt"] < utcnow():
            raise _fail(400, "expired_token", ERROR_CODES["EXPIRED_USER_CODE"])

        session = await ctx.get_session()
        user_id = session["user"]["id"] if session else None
        if user_id and not record.get("userId") and record["status"] == "pending":
            # Guarded claim (status=pending AND userId IS NULL): a claim that already landed
            # between our read and this write wins the guard (TS GHSA-cq3f-vc6p-68fh fix).
            claimed = await ctx.adapter.increment_one(
                "deviceCode",
                [
                    Where("id", record["id"]),
                    Where("status", "pending"),
                    Where("userId", None, "eq"),
                ],
                set={"userId": user_id},
            )
            if claimed is not None:
                record["userId"] = user_id

        owner = user_id is not None and record.get("userId") == user_id
        response: dict[str, Any] = {}
        if owner and self.grant is not None:
            response.update(self.grant.get_verification_context(record) or {})
        response.update({"user_code": user_code, "status": record["status"]})
        if owner:
            for key, value in (
                ("client_id", record.get("clientId")),
                ("scope", record.get("scope")),
            ):
                response[key] = value
                if value is None:  # TS undefined drops the key, grant context included
                    del response[key]
        return AuthResponse(body=response)

    async def _device_approve(self, ctx: Ctx) -> AuthResponse:
        return await self._resolve(ctx, "approved", "approve")

    async def _device_deny(self, ctx: Ctx) -> AuthResponse:
        return await self._resolve(ctx, "denied", "deny")

    async def _resolve(self, ctx: Ctx, new_status: str, verb: str) -> AuthResponse:
        session = await ctx.get_session()
        if session is None:
            raise _fail(401, "unauthorized", ERROR_CODES["AUTHENTICATION_REQUIRED"])

        body, _ = _request_body(ctx)
        user_code = body.get("userCode")
        if not isinstance(user_code, str) or not user_code:
            raise _fail(400, "invalid_request", "'userCode' is required")
        record = await find_device_code_by_user_code(ctx, user_code)
        if record is None:
            raise _fail(400, "invalid_request", ERROR_CODES["INVALID_USER_CODE"])
        if record["expiresAt"] < utcnow():
            raise _fail(400, "expired_token", ERROR_CODES["EXPIRED_USER_CODE"])
        if record["status"] != "pending":
            raise _fail(400, "invalid_request", ERROR_CODES["DEVICE_CODE_ALREADY_PROCESSED"])
        if not record.get("userId"):
            raise _fail(400, "invalid_request", ERROR_CODES["DEVICE_CODE_NOT_CLAIMED"])

        user_id = session["user"]["id"]
        if record["userId"] != user_id:
            raise _fail(
                403, "access_denied", f"You are not authorized to {verb} this device authorization"
            )

        await ctx.adapter.update(
            "deviceCode", [Where("id", record["id"])], {"status": new_status, "userId": user_id}
        )
        return AuthResponse(body={"success": True})
