"""device-authorization plugin — OAuth 2.0 Device Authorization Grant (RFC 8628).

TV/CLI login: a device mints a `device_code`/`user_code` pair, shows the user_code to
the user, and polls `/device/token` while the user visits `/device` on a second screen
(phone/laptop) to approve or deny it.

Verified against TS ``packages/better-auth/src/plugins/device-authorization/``
(``index.ts``, ``routes.ts``, ``schema.ts``, ``error-codes.ts``) at v1.6.23. Every error
in this plugin is OAuth-shaped on the wire (``{"error": ..., "error_description": ...}``,
RFC 6749 style) rather than this port's generic ``{"code", "message"}`` APIError body, so
endpoints return :class:`AuthResponse` directly instead of raising ``APIError``.

Redemption of an approved code is atomic (``adapter.consume_one`` — delete-and-return, TS
``consumeOne``): concurrent pollers race on the same delete, exactly one wins the row and
mints a session, every other caller gets ``None`` back and is rejected. The `/device`
claim of a pending, unbound code and the `/device/token` polling-interval bump both use
``adapter.increment_one`` (guarded compare-and-swap, TS ``incrementOne``) so a stale read
can never clobber a write that landed first — this closes the same race TS's own
GHSA-cq3f-vc6p-68fh fix targets, and hardens the (TS-unguarded) `lastPolledAt` bump the
same way.
"""

from __future__ import annotations

import inspect
import re
from datetime import timedelta
from typing import Any, ClassVar
from urllib.parse import parse_qsl, urlencode, urljoin, urlsplit, urlunsplit

from ..adapters.base import Where
from ..crypto import generate_random_string
from ..plugins import Plugin, Route
from ..schema import Field, Schema
from ..session import utcnow
from ..types import AuthResponse, Ctx

#: TS ``DEVICE_AUTHORIZATION_ERROR_CODES`` (error-codes.ts) — exact strings, surfaced on
#: ``auth.error_codes``. These are the internal error *messages*; the wire-visible OAuth
#: error *codes* (``slow_down``, ``invalid_grant``, ...) are the literals used below.
ERROR_CODES: dict[str, str] = {
    "INVALID_DEVICE_CODE": "Invalid device code",
    "EXPIRED_DEVICE_CODE": "Device code has expired",
    "EXPIRED_USER_CODE": "User code has expired",
    "AUTHORIZATION_PENDING": "Authorization pending",
    "ACCESS_DENIED": "Access denied",
    "INVALID_USER_CODE": "Invalid user code",
    "DEVICE_CODE_ALREADY_PROCESSED": "Device code already processed",
    "DEVICE_CODE_NOT_CLAIMED": (
        "Device code has not been claimed by a verifying session; call `GET /device` "
        "with the `user_code` while signed in before approving or denying"
    ),
    "POLLING_TOO_FREQUENTLY": "Polling too frequently",
    "USER_NOT_FOUND": "User not found",
    "FAILED_TO_CREATE_SESSION": "Failed to create session",
    "INVALID_DEVICE_CODE_STATUS": "Invalid device code status",
    "AUTHENTICATION_REQUIRED": "Authentication required",
}

#: TS ``schema.ts`` — a brand-new top-level table (no ``id``/``createdAt``/``updatedAt``
#: declared, matching TS exactly; ``id`` is auto-generated by the adapter on create).
_SCHEMA: Schema = {
    "deviceCode": {
        "deviceCode": Field("string", required=True),
        "userCode": Field("string", required=True),
        "userId": Field("string", required=False),
        "expiresAt": Field("datetime", required=True),
        "status": Field("string", required=True),
        "lastPolledAt": Field("datetime", required=False),
        "pollingInterval": Field("number", required=False),
        "clientId": Field("string", required=False),
        "scope": Field("string", required=False),
    },
}

_GRANT_TYPE = "urn:ietf:params:oauth:grant-type:device_code"
#: TS ``generateRandomString(length, "a-z", "A-Z", "0-9")`` (routes.ts defaultGenerateDeviceCode).
_DEVICE_CODE_ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
#: TS ``defaultCharset`` (routes.ts) — Crockford-ish, no ambiguous I/O/0/1.
_USER_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"

# --- time-string parsing (TS utils/time.ts `ms()`, positive-duration subset) -----------
#
# ponytail: expiresIn/interval are always positive durations for this plugin, so the sign
# prefix ("+"/"-") and "ago"/"from now" suffix TS's `ms()` also accepts are skipped here —
# add if a config value ever needs relative/negative time semantics (it doesn't today).

_SEC = 1000
_MIN = _SEC * 60
_HOUR = _MIN * 60
_DAY = _HOUR * 24
_WEEK = _DAY * 7
_MONTH = _DAY * 30
_YEAR = _DAY * 365.25

_UNIT_MS: dict[str, float] = {
    "s": _SEC, "sec": _SEC, "secs": _SEC, "second": _SEC, "seconds": _SEC,
    "m": _MIN, "min": _MIN, "mins": _MIN, "minute": _MIN, "minutes": _MIN,
    "h": _HOUR, "hr": _HOUR, "hrs": _HOUR, "hour": _HOUR, "hours": _HOUR,
    "d": _DAY, "day": _DAY, "days": _DAY,
    "w": _WEEK, "week": _WEEK, "weeks": _WEEK,
    "mo": _MONTH, "month": _MONTH, "months": _MONTH,
    "y": _YEAR, "yr": _YEAR, "yrs": _YEAR, "year": _YEAR, "years": _YEAR,
}  # fmt: skip

_TIME_RE = re.compile(
    r"^(\d+|\d+\.\d+) ?"
    r"(seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|w|months?|mo|years?|yrs?|y)$",
    re.IGNORECASE,
)


def _parse_time_ms(value: str) -> int:
    """``"30m"``/``"5s"``/``"1h"`` -> milliseconds (TS ``ms()``, utils/time.ts). Raises
    ``ValueError`` on an unparseable string — the eager-validation equivalent of zod's
    ``deviceAuthorizationOptionsSchema.parse()`` throwing at plugin construction."""
    if not isinstance(value, str):
        raise ValueError(f"Invalid time string format: {value!r}")
    match = _TIME_RE.match(value.strip())
    if not match:
        raise ValueError(
            f'Invalid time string format: "{value}". Use formats like "30m", "5s", "1h", etc.'
        )
    amount = float(match.group(1))
    unit = match.group(2).lower()
    return round(amount * _UNIT_MS[unit])


async def _maybe_await(value: Any) -> Any:
    return await value if inspect.isawaitable(value) else value


def _oauth_error(status: int, error: str, description: str) -> AuthResponse:
    """Every error this plugin raises is OAuth-shaped (RFC 6749 ``{error,
    error_description}``), never this port's generic ``{code, message}`` — so endpoints
    return this directly instead of raising ``APIError`` (which the core dispatcher
    always renders as ``{code, message}``)."""
    return AuthResponse(status=status, body={"error": error, "error_description": description})


def _required_str(body: dict[str, Any], key: str) -> str | None:
    value = body.get(key)
    return value if isinstance(value, str) and value else None


def _build_verification_uris(
    verification_uri: str | None, base_url: str, user_code: str
) -> tuple[str, str]:
    """Resolve ``verification_uri`` (default ``/device``) against ``base_url`` (TS ``new
    URL(uri) | new URL(uri, baseURL)``) and derive the ``...?user_code=`` variant,
    preserving any query params the configured URI already carries."""
    resolved = urljoin(base_url, verification_uri or "/device")
    parts = urlsplit(resolved)
    params = [(k, v) for k, v in parse_qsl(parts.query, keep_blank_values=True) if k != "user_code"]
    params.append(("user_code", user_code))
    complete = urlunsplit(
        (parts.scheme, parts.netloc, parts.path, urlencode(params), parts.fragment)
    )
    return resolved, complete


class DeviceAuthorizationPlugin(Plugin):
    """TS ``deviceAuthorization()`` — see module docstring for the source files."""

    id = "device-authorization"
    schema: ClassVar[Schema] = _SCHEMA
    error_codes: ClassVar[dict[str, str]] = ERROR_CODES

    def __init__(
        self,
        *,
        expires_in: str = "30m",
        interval: str = "5s",
        device_code_length: int = 40,
        user_code_length: int = 8,
        generate_device_code: Any = None,
        generate_user_code: Any = None,
        validate_client: Any = None,
        on_device_auth_request: Any = None,
        verification_uri: str | None = None,
    ) -> None:
        _parse_time_ms(expires_in)
        _parse_time_ms(interval)
        if not isinstance(device_code_length, int) or device_code_length <= 0:
            raise ValueError("device_code_length must be a positive integer")
        if not isinstance(user_code_length, int) or user_code_length <= 0:
            raise ValueError("user_code_length must be a positive integer")
        if verification_uri is not None and not isinstance(verification_uri, str):
            raise ValueError("verification_uri must be a string")

        self.expires_in = expires_in
        self.interval = interval
        self.device_code_length = device_code_length
        self.user_code_length = user_code_length
        self.generate_device_code = generate_device_code
        self.generate_user_code = generate_user_code
        self.validate_client = validate_client
        self.on_device_auth_request = on_device_auth_request
        self.verification_uri = verification_uri

    def routes(self) -> list[Route]:
        return [
            ("POST", "/device/code", self._device_code),
            ("POST", "/device/token", self._device_token),
            ("GET", "/device", self._device_verify),
            ("POST", "/device/approve", self._device_approve),
            ("POST", "/device/deny", self._device_deny),
        ]

    # --- code generation ----------------------------------------------------------------

    async def _generate_device_code(self) -> str:
        if self.generate_device_code is not None:
            return await _maybe_await(self.generate_device_code())
        return generate_random_string(self.device_code_length, alphabet=_DEVICE_CODE_ALPHABET)

    async def _generate_user_code(self) -> str:
        if self.generate_user_code is not None:
            return await _maybe_await(self.generate_user_code())
        return generate_random_string(self.user_code_length, alphabet=_USER_CODE_ALPHABET)

    # --- endpoints ------------------------------------------------------------------------

    async def _device_code(self, ctx: Ctx) -> AuthResponse:
        body = ctx.body()
        client_id = _required_str(body, "client_id")
        if client_id is None:
            return _oauth_error(400, "invalid_request", "'client_id' is required")

        if self.validate_client is not None and not await _maybe_await(
            self.validate_client(client_id)
        ):
            return _oauth_error(400, "invalid_client", "Invalid client ID")

        if self.on_device_auth_request is not None:
            await _maybe_await(self.on_device_auth_request(client_id, body.get("scope")))

        device_code_value = await self._generate_device_code()
        user_code_value = await self._generate_user_code()
        expires_in_ms = _parse_time_ms(self.expires_in)
        polling_interval_ms = _parse_time_ms(self.interval)
        expires_at = utcnow() + timedelta(milliseconds=expires_in_ms)

        await ctx.adapter.create(
            "deviceCode",
            {
                "deviceCode": device_code_value,
                "userCode": user_code_value,
                # an empty user_id is treated as omitted, per RFC 8628 section 3.1
                "userId": body.get("user_id") or None,
                "expiresAt": expires_at,
                "status": "pending",
                "pollingInterval": polling_interval_ms,
                "clientId": client_id,
                "scope": body.get("scope"),
            },
        )

        base_url = f"{ctx.auth.base_url}{ctx.auth.base_path}"
        verification_uri, verification_uri_complete = _build_verification_uris(
            self.verification_uri, base_url, user_code_value
        )

        return AuthResponse(
            body={
                "device_code": device_code_value,
                "user_code": user_code_value,
                "verification_uri": verification_uri,
                "verification_uri_complete": verification_uri_complete,
                "expires_in": expires_in_ms // 1000,
                "interval": polling_interval_ms // 1000,
            },
            headers=[("Cache-Control", "no-store")],
        )

    async def _device_token(self, ctx: Ctx) -> AuthResponse:
        body = ctx.body()
        grant_type = body.get("grant_type")
        device_code = _required_str(body, "device_code")
        client_id = _required_str(body, "client_id")
        if grant_type != _GRANT_TYPE or device_code is None or client_id is None:
            return _oauth_error(400, "invalid_request", "Invalid device token request")

        if self.validate_client is not None and not await _maybe_await(
            self.validate_client(client_id)
        ):
            return _oauth_error(400, "invalid_grant", "Invalid client ID")

        record = await ctx.adapter.find_one("deviceCode", [Where("deviceCode", device_code)])
        if record is None:
            return _oauth_error(400, "invalid_grant", ERROR_CODES["INVALID_DEVICE_CODE"])

        if record.get("clientId") and record["clientId"] != client_id:
            return _oauth_error(400, "invalid_grant", "Client ID mismatch")

        now = utcnow()
        if record.get("lastPolledAt") and record.get("pollingInterval"):
            elapsed_ms = (now - record["lastPolledAt"]).total_seconds() * 1000
            if elapsed_ms < record["pollingInterval"]:
                return _oauth_error(400, "slow_down", ERROR_CODES["POLLING_TOO_FREQUENTLY"])

        # Guarded bump (CAS on the previously-read lastPolledAt): a poll that raced us
        # between the read above and this write loses the guard and is treated as
        # slow_down too, instead of silently clobbering the other poll's timestamp.
        polled = await ctx.adapter.increment_one(
            "deviceCode",
            [Where("id", record["id"]), Where("lastPolledAt", record.get("lastPolledAt"), "eq")],
            set={"lastPolledAt": now},
        )
        if polled is None:
            return _oauth_error(400, "slow_down", ERROR_CODES["POLLING_TOO_FREQUENTLY"])
        record = polled

        if record["expiresAt"] < now:
            await ctx.adapter.delete("deviceCode", [Where("id", record["id"])])
            return _oauth_error(400, "expired_token", ERROR_CODES["EXPIRED_DEVICE_CODE"])

        if record["status"] == "pending":
            return _oauth_error(400, "authorization_pending", ERROR_CODES["AUTHORIZATION_PENDING"])

        if record["status"] == "denied":
            await ctx.adapter.delete("deviceCode", [Where("id", record["id"])])
            return _oauth_error(400, "access_denied", ERROR_CODES["ACCESS_DENIED"])

        if record["status"] == "approved" and record.get("userId"):
            # Atomic single-claim gate: concurrent pollers race on this delete-and-return,
            # only the one that removes the row may issue a session (see module docstring).
            claimed = await ctx.adapter.consume_one(
                "deviceCode", [Where("deviceCode", device_code), Where("status", "approved")]
            )
            if not claimed or not claimed.get("userId"):
                return _oauth_error(400, "invalid_grant", ERROR_CODES["INVALID_DEVICE_CODE"])

            user = await ctx.adapter.find_one("user", [Where("id", claimed["userId"])])
            if user is None:
                return _oauth_error(500, "server_error", ERROR_CODES["USER_NOT_FOUND"])

            session = await ctx.internal.create_session(user["id"])
            if session is None:
                return _oauth_error(500, "server_error", ERROR_CODES["FAILED_TO_CREATE_SESSION"])

            ctx.new_session = {"session": session, "user": user}

            expires_in = int((session["expiresAt"] - utcnow()).total_seconds())
            return AuthResponse(
                body={
                    "access_token": session["token"],
                    "token_type": "Bearer",
                    "expires_in": expires_in,
                    "scope": claimed.get("scope") or "",
                },
                headers=[("Cache-Control", "no-store"), ("Pragma", "no-cache")],
            )

        return _oauth_error(500, "server_error", ERROR_CODES["INVALID_DEVICE_CODE_STATUS"])

    async def _device_verify(self, ctx: Ctx) -> AuthResponse:
        user_code = ctx.request.query.get("user_code")
        if not user_code:
            return _oauth_error(400, "invalid_request", "'user_code' is required")
        clean_user_code = user_code.replace("-", "")

        record = await ctx.adapter.find_one("deviceCode", [Where("userCode", clean_user_code)])
        if record is None:
            return _oauth_error(400, "invalid_request", ERROR_CODES["INVALID_USER_CODE"])

        if record["expiresAt"] < utcnow():
            return _oauth_error(400, "expired_token", ERROR_CODES["EXPIRED_USER_CODE"])

        session = await ctx.get_session()
        user_id = (session or {}).get("user", {}).get("id") if session else None
        if user_id and not record.get("userId") and record["status"] == "pending":
            # Guarded claim (status=pending AND userId IS NULL): a claim that already
            # landed between our read and this write wins the guard; we silently no-op
            # rather than overwrite it (TS GHSA-cq3f-vc6p-68fh fix).
            await ctx.adapter.increment_one(
                "deviceCode",
                [
                    Where("id", record["id"]),
                    Where("status", "pending"),
                    Where("userId", None, "eq"),
                ],
                set={"userId": user_id},
            )

        return AuthResponse(body={"user_code": user_code, "status": record["status"]})

    async def _device_approve(self, ctx: Ctx) -> AuthResponse:
        return await self._resolve(ctx, "approved", "approve")

    async def _device_deny(self, ctx: Ctx) -> AuthResponse:
        return await self._resolve(ctx, "denied", "deny")

    async def _resolve(self, ctx: Ctx, new_status: str, verb: str) -> AuthResponse:
        session = await ctx.get_session()
        if session is None:
            return _oauth_error(401, "unauthorized", ERROR_CODES["AUTHENTICATION_REQUIRED"])

        body = ctx.body()
        user_code = _required_str(body, "userCode")
        if user_code is None:
            return _oauth_error(400, "invalid_request", "'userCode' is required")
        clean_user_code = user_code.replace("-", "")

        record = await ctx.adapter.find_one("deviceCode", [Where("userCode", clean_user_code)])
        if record is None:
            return _oauth_error(400, "invalid_request", ERROR_CODES["INVALID_USER_CODE"])

        if record["expiresAt"] < utcnow():
            return _oauth_error(400, "expired_token", ERROR_CODES["EXPIRED_USER_CODE"])

        if record["status"] != "pending":
            already_processed = ERROR_CODES["DEVICE_CODE_ALREADY_PROCESSED"]
            return _oauth_error(400, "invalid_request", already_processed)

        if not record.get("userId"):
            return _oauth_error(400, "invalid_request", ERROR_CODES["DEVICE_CODE_NOT_CLAIMED"])

        user_id = session["user"]["id"]
        if record["userId"] != user_id:
            return _oauth_error(
                403, "access_denied", f"You are not authorized to {verb} this device authorization"
            )

        await ctx.adapter.update(
            "deviceCode", [Where("id", record["id"])], {"status": new_status, "userId": user_id}
        )
        return AuthResponse(body={"success": True})
